name: Build Extension Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'docs/**'

jobs:
  build-vsix:
    runs-on: ubuntu-latest

    steps:
      - name: Set up, install and build
        uses: ./.github/actions/build

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v7
        with:
          name: swupdate-lang-vsix
          path: swupdate-lang.vsix
          if-no-files-found: error
